version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "notification:1:1,filnotification:1:1"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  notification_service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - redis

  layer_consumer:
    build:
      context: ./layer_consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka

  end_consumer:
    build:
      context: ./end_consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
